### ISSUE TITLE
Error when attempting to insert a single tile

### ISSUE THREAD

**Issue by powerspowers** [afruehstueck/tileGAN#7]
In the client when I select a tile cluster and then click on a spot on the painted image I get the following error. I am able to generate a random region (eg. 5x5) and see the results, but a single tile placement gives this:

<ImageViewer> left mouse button clicked at PySide2.QtCore.QPoint(775, 654)!
parent gets mouseReleaseEvent
mouse pressed in 11
mouse pressed in 11
mouse pressed in 11
mouse pressed in 11
mouse pressed in 11
mouse pressed in 11
mouse pressed in 11
parent gets mouseReleaseEvent
mouse pressed in 8
<ImageViewer> left mouse button clicked at PySide2.QtCore.QPoint(722, 257)!
<ImageViewer> mouseReleaseEvent at PySide2.QtCore.QPoint(491, 243)
<ImageViewer> dropped latent of class 8 at (4, 2)
Traceback (most recent call last):
  File "tileGAN_client.py", line 539, in mouseReleaseEvent
    self.dropLatent(self.latentCluster, event.pos(), modifiers)
  File "tileGAN_client.py", line 748, in dropLatent
    output, undoCount = np.asarray(tf_manager.putLatent(gridCoords.x(), gridCoords.y(), latentCluster)._getvalue())
  File "C:\Users\Powerpop\Anaconda3\lib\multiprocessing\managers.py", line 724, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "C:\Users\Powerpop\Anaconda3\lib\multiprocessing\managers.py", line 609, in _create
    id, exposed = dispatch(conn, None, 'create', (typeid,)+args, kwds)
  File "C:\Users\Powerpop\Anaconda3\lib\multiprocessing\managers.py", line 82, in dispatch
    raise convert_to_error(kind, result)
multiprocessing.managers.RemoteError:
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Powerpop\Anaconda3\lib\multiprocessing\managers.py", line 201, in handle_request
    result = func(c, *args, **kwds)
  File "C:\Users\Powerpop\Anaconda3\lib\multiprocessing\managers.py", line 388, in create
    obj = callable(*args, **kwds)
  File "tileGAN_server.py", line 934, in putLatent
    self.putOnUndoStack(self.latentList)
  File "tileGAN_server.py", line 955, in putOnUndoStack
    self.undoStack = np.concatenate((self.undoStack[1:], np.expand_dims(latentList, axis=0)), axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 25 and the array at index 1 has size 100
---------------------------------------------------------------------------
<ImageViewer> left mouse button clicked at PySide2.QtCore.QPoint(1202, 294)!
<ImageViewer> mouseReleaseEvent at PySide2.QtCore.QPoint(944, 278)
<ImageViewer> dropped latent of class 8 at (7, 2)
Traceback (most recent call last):
  File "tileGAN_client.py", line 539, in mouseReleaseEvent
    self.dropLatent(self.latentCluster, event.pos(), modifiers)
  File "tileGAN_client.py", line 748, in dropLatent
    output, undoCount = np.asarray(tf_manager.putLatent(gridCoords.x(), gridCoords.y(), latentCluster)._getvalue())
  File "C:\Users\Powerpop\Anaconda3\lib\multiprocessing\managers.py", line 724, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "C:\Users\Powerpop\Anaconda3\lib\multiprocessing\managers.py", line 609, in _create
    id, exposed = dispatch(conn, None, 'create', (typeid,)+args, kwds)
  File "C:\Users\Powerpop\Anaconda3\lib\multiprocessing\managers.py", line 82, in dispatch
    raise convert_to_error(kind, result)
multiprocessing.managers.RemoteError:
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Powerpop\Anaconda3\lib\multiprocessing\managers.py", line 201, in handle_request
    result = func(c, *args, **kwds)
  File "C:\Users\Powerpop\Anaconda3\lib\multiprocessing\managers.py", line 388, in create
    obj = callable(*args, **kwds)
  File "tileGAN_server.py", line 934, in putLatent
    self.putOnUndoStack(self.latentList)
  File "tileGAN_server.py", line 955, in putOnUndoStack
    self.undoStack = np.concatenate((self.undoStack[1:], np.expand_dims(latentList, axis=0)), axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 25 and the array at index 1 has size 100
---------------------------------------------------------------------------

**Comment by afruehstueck** [comment]
You may have to (re-)select a latent cluster (from the available clusters on the bottom) first in order to be able to paint. 
![tilegan_click_paint](https://user-images.githubusercontent.com/19155913/74332450-c8faa200-4da6-11ea-94a5-a39575951f24.gif)

**Comment by powerspowers** [comment]
I do that and don't get the floating square over the canvas and clicking gives the index range error. Going to upgrade to TF 1.8 and then see what happens.
